//
//  VacAppModul.swift
//  rff
//
//  Created by Riyadh Foods Industrial Co. on 24/07/2018.
//  Copyright © 2018 Riyadh Foods Industrial Co. All rights reserved.
//

import Foundation
public class VacAppModul{
    public var Cmt_Name : String = ""
    public var Cmt_Comment : String = ""
    public var WorkFlow_Empid : String = ""
    public var WorkFlow_EmpName : String = ""
    public var WorkFlow_EmpRole : String = ""
    public var WorkFlow_EmpStatus : String = ""
    public var WorkFlow_EmpTransDate : String = ""
    public var S_BasicSal : String = ""
    public var S_Allowances : String = ""
    public var S_Total : String = ""
    public var S_DeductAmount : String = ""
    public var S_NetAmount : String = ""
    public var V_BasicSal : String = ""
    public var V_Allowances : String = ""
    public var V_Total : String = ""
    public var V_DeductAmount : String = ""
    public var V_NetAmount : String = ""
    public var Tck_Price : String = ""
    public var Tck_Amount : String = ""
    public var Tck_Percent1 : String = ""
    public var Tck_DeductAmount : String = ""
    public var Tck_NetAmount : String = ""
    public var Deduction_Grid_ID : String = ""
    public var Deduction_Grid_DeductionType : String = ""
    public var Deduction_Grid_DeductibleAmount : String = ""
    public var Salary_Deduction : String = ""
    public var NumberofDays : String = ""
    public var LeaveStartDate : String = ""
    public var ReturnDate : String = ""
    public var RequestDate : String = ""
    public var VacationType : String = ""
    public var ExitReEntry : String = ""
    public var ExitReEntryDays : String = ""
    public var VacTypeAdmin : String = ""
    public var VacationDays : String = ""
    public var TicketRequired : String = ""
    public var Vacation_Number : String = ""
    public var Requested : String = ""
    public var Total_SettlementAmount : String = ""
    public var EmpName : String = ""
    public var JoinDate : String = ""
    public var StartDate : String = ""
    public var ManagerName : String = ""
    public var JobDesc : String = ""
    public var SubJobDesc : String = ""
    public var Department : String = ""
    public var Nationality : String = ""
    public var City : String = ""
    public var VacationDays_Details : String = ""
    public var Used_Details : String = ""
    public var Remaining_Detail : String = ""
    public var Name_Companion : String = ""
    public var City_Companion : String = ""
    public var DOB_Companion : String = ""
    public var VisaRequest_Companion : String = ""
}
